kind: Service
apiVersion: v1
metadata:
  name: nfs-server-service
  labels:
    cluster-type: private
spec:
  selector:
    cluster-type: private
    name: nfs-server
  type: ClusterIP
  ports:
    - port: 2049
      targetPort: 2049
