apiVersion: hykufe.com/v1alpha1
kind: HorovodJob
metadata:
  name: horovod-job-example
  labels:
    "volcano.sh/job-type": Horovod
spec:
  schedulerName: volcano

  dataShareMode:
    nfsMode:
      ipAddress: ???
      path: ???
  dataSources:
    - name: "s3-train"
      s3Source:
        s3SecretName: "s3-secret"
        directory : data
  volumes:
    - volumeClaimName: "data-volume"
      mountPath: "/data"
  master:
    replicas: 1
    name: master
    policies:
      - event: TaskCompleted
        action: CompleteJob
    template:
      spec:
        containers:
          - command:
              - /bin/bash
              - -c
              - |
                set -o pipefail;
                WORKER_HOST=`cat /etc/volcano/worker.host | tr "\n" ","`;
                mkdir -p /var/run/sshd; /usr/sbin/sshd;
                mkdir -p /result/log;
                sleep 15;
                mpiexec --allow-run-as-root --host ${WORKER_HOST} -np 3 python tensorflow_mnist_lm.py 2>&1 | tee /result/log/mpi_log;
                echo $? > /result/exit_code;
            image: volcanosh/horovod-tf-mnist:0.5
            name: master
            ports:
              - containerPort: 22
                name: job-port
            resources:
              requests:
                cpu: "500m"
                memory: "1024Mi"
              limits:
                cpu: "500m"
                memory: "1024Mi"
        restartPolicy: OnFailure
        imagePullSecrets:
          - name: default-secret
  worker:
    replicas: 2
    name: worker
    template:
      spec:
        containers:
          - command:
              - /bin/sh
              - -c
              - |
                mkdir -p /var/run/sshd; /usr/sbin/sshd -D;
            image: volcanosh/horovod-tf-mnist:0.5
            name: worker
            ports:
              - containerPort: 22
                name: job-port
            resources:
              requests:
                cpu: "1000m"
                memory: "1024Mi"
              limits:
                cpu: "1000m"
                memory: "1024Mi"
        restartPolicy: OnFailure
        imagePullSecrets:
          - name: default-secret
---
