kind: ConfigMap
apiVersion: v1
metadata:
  name: horovod-cm
data:
  sidecar.run: |
    #!/bin/sh
    set -x
    sleep 5

    # find mpi process pid
    while :
    do
      horovod_pid=$(ps -A | grep mpiexec | awk '$4 !~ /grep/ {print $1}')
      if [ "$horovod_pid" != "" ]
      then
        echo "found MPI process! pid is : $horovod_pid"
        break
      fi
      sleep 1
    done

    while :
    do
      # 계속 mpi process를 감시한다. 만약 죽어있다면 파일로 저장된 exit code를 참조한다.
      horovod_pid=$(ps -A | grep mpiexec | awk '$4 !~ /grep/ {print $1}')
      if [ "$horovod_pid" != "" ]
      then
        echo "found MPI process! pid is : $horovod_pid"
        sleep 5
        continue
      fi

      sleep 5

      if [ -f "/result/exit_code" ]
      then
        echo "found exit code from MPI Process"
        break
      else # 만약 파일이 없다면 제대로 종료된게 아니므로 종료한다.
        exit 1
      fi
      sleep 1
    done

    exit_code=$(</result/exit_code)
    if [ "$exit_code" == "0" ]
    then
      # if exit code is 0 is train is normally finished
      # send S3
      if [ ! -z "$SAVE_TO_S3" ]
      then
        echo "Upload Log, Model to S3!"
        aws s3 cp /result/log s3://${AWS_S3_BUCKET}/horovod-result/${JOB_NAME}/log
        aws s3 cp /result/model s3://${AWS_S3_BUCKET}/horovod-result/${JOB_NAME}/model
      fi
    else # abnormally finished
      if [ ! -z "$SAVE_TO_S3" ]
      then
        echo "horovod job is abnormally finished"
        if [ -d "/result/checkpoint" ]
        then
          echo "Upload Checkpoint to S3!"
          aws s3 cp /result/checkpoint s3://${AWS_S3_BUCKET}/horovod-result/${JOB_NAME}/checkpoint
        fi
      fi
      exit 1;
    fi




