kind: ConfigMap
apiVersion: v1
metadata:
  name: horovod-cm
data:
  sidecar.run: |
    #!/bin/sh
    set -x
    sleep 5

    # find mpi process pid
    while :
    do
      mpi_pid=$(ps -A | grep mpiexec | awk '{print $1}')
      if [ "$mpi_pid" != "" ]
      then
        echo "found MPI process! pid is : $mpi_pid"
        break
      fi
      sleep 1
    done

    while :
    do
      echo "do something"
      sleep 10
    done




